
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Product Table</title>
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">   
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<link rel="stylesheet" href="http://cdn.datatables.net/1.10.2/css/jquery.dataTables.min.css"></style>
<script type="text/javascript" src="http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</head>
<body>
      
<table id="product" class="table table-striped" >
<tbody>
      <h2>Terms of Use / User Agreement</h2>
 
This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.SparksFly.com website.
.
 
Introduction
Welcome to the SparksFly.com (“Website” or “SparksFly.com”) service provided by SparksFly Technologies Pvt Ltd.. This website, and the associated domain, is owned and operated by SparksFly Technologies Pvt Ltd.., or its affiliates ('SparksFly Technologies Pvt Ltd.' or 'SparksFly', 'we' or 'us' ). With its Head office at 401, Trade Centre, North Main Road, Koregaon Park, Pune ‾ 411001, Maharashtra, India. In using the SparksFly.com service, of SparksFly Technologies Pvt Ltd. you are deemed to have accepted the Terms and Conditions of the agreement listed below or as may be revised from time to time, which is, for an indefinite period and you understand and agree that you are bound by such terms till the time you access this website, and till such time any service subscribed to, or associated with this Website is provided to you
We reserve the right to change these terms & conditions from time to time without any obligation to inform you and it is your responsibility to look through them as often as possible.
Ownership of rights

All rights, including copyright, in this website are owned by or licensed to SparksFly Technologies Pvt Ltd.. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of SparksFly Technologies Pvt Ltd.. You may not modify, distribute or re-post something on this website for any purpose.

        </tbody>  
      </table>  
      
     
  <nav class="navbar navbar-inverse navbar-fixed-bottom">

<h5><b><font color = "White">About</font> </b><span class="label label-default">Spreading happiness for decades</span></h5>
<div class = "container">


</div>
</div>

</nav>
</body>
</html>
